In [ ]:
import pandas as pd

df = pd.read_csv("mpd2023_web.csv", header=2)

df.head()

# year range
start_year = 1950
end_year   = 2000

# Filter the dataset by year and keep the countries of interest
# df["year"] selects the 'year' column
# df["year"] >= start_year creates a True/False condition
# df["year"] <= end_year creates another True/False condition
# The & symbol means "AND" (both conditions must be true)

# df.loc[rows, columns] is label-based indexing:
#   - rows: which rows to keep
#   - columns: which columns to keep

# .copy() creates a new DataFrame
# filter once, then slice countries
df_range = df.loc[(df["year"] >= start_year) & (df["year"] <= end_year), ["year", "ARG", "BRA", "CHL"]].copy()


# Select only the 'year' and Argentina ('ARG') columns
# .rename() changes the column name from 'ARG' to 'gdp_pc'
# This makes all country datasets use the same column name

# make the three country "variables" (each is year + one GDP column)
argentina = df_range[["year", "ARG"]].rename(columns={"ARG": "gdp_pc"})
brazil    = df_range[["year", "BRA"]].rename(columns={"BRA": "gdp_pc"})
chile     = df_range[["year", "CHL"]].rename(columns={"CHL": "gdp_pc"})

# show first 10 rows of each
print("Argentina (first 10 rows):")
display(argentina.head(10))

print("Brazil (first 10 rows):")
display(brazil.head(10))

print("Chile (first 10 rows):")
display(chile.head(10))

Argentina (first 10 rows):

       year   gdp_pc
704  1950.0   7,949
705  1951.0   8,086
706  1952.0   7,519
707  1953.0   7,769
708  1954.0   7,938
709  1955.0   8,348
710  1956.0   8,424
711  1957.0   8,705
712  1958.0   9,083
713  1959.0   8,354

Brazil (first 10 rows):

       year   gdp_pc
704  1950.0   2,236
705  1951.0   2,279
706  1952.0   2,377
707  1953.0   2,418
708  1954.0   2,531
709  1955.0   2,675
710  1956.0   2,672
711  1957.0   2,793
712  1958.0   3,005
713  1959.0   3,201

Chile (first 10 rows):

       year   gdp_pc
704  1950.0   5,880
705  1951.0   6,001
706  1952.0   6,252
707  1953.0   6,582
708  1954.0   6,237
709  1955.0   6,341
710  1956.0   6,285
711  1957.0   6,758
712  1958.0   6,958
713  1959.0   6,409